- model: deepseek-chat
  provider: deepseek
  enabled: true
  api_key: ${DEEPSEEK_API_KEY}
  base_url: https://api.deepseek.com/v1
  max_tokens: 4096
  temperature: 0
  top_p: 1.0

- model: gpt-4.1
  provider: openai
  enabled: true
  api_key: ${OPENAI_API_KEY}
  base_url: https://api.openai.com/v1
  max_tokens: 4096
  temperature: 0
  top_p: 1.0

- model: deepseek-coder
  provider: deepseek
  enabled: true
  api_key: ${DEEPSEEK_API_KEY}
  base_url: https://api.deepseek.com/v1
  max_tokens: 4096
  temperature: 0
  top_p: 1.0